# Purpose: Helps CircleCI create the K8s deploy SIS poller image.
# Usage: buildah build -t sispoller:latest -f Dockerfile.deploy
FROM alpine:latest as sispoller

RUN apk update

# Create a user
RUN addgroup -S appgroup &&\ 
    adduser -S appuser --home /home/appuser --shell /bin/bash --disabled-password --gecos -G appgroup

ADD sis_poller /usr/local/bin

USER appuser
WORKDIR /home/appuser
